### ISSUE TITLE
Low level driver for stm32 sdio

### ISSUE THREAD

**Issue by SimonTechv** [tuxera/reliance-edge#39]
Studying the lower-level driver for stm32, I'm a little confused. Take a look at this code:
```
if(IS_ALIGNED_PTR(pBuffer, sizeof(uint32_t)))
    {
        bSdError = BSP_SD_WriteBlocks_DMA(CAST_AWAY_CONST(void, pBuffer), ullSectorStart, ulSectorCount);

        if(bSdError != MSD_OK)
        {
            redStat = -RED_EIO;
        }
      #if SD_STATUS_TIMEOUT > 0U
        else
        {
            redStat = CheckStatus();
        }
      #endif
    }
    else
    {
        uint32_t ulSectorIdx;

        for(ulSectorIdx = 0U; ulSectorIdx < ulSectorCount; ulSectorIdx++)
        {
            const uint8_t *pbBuffer = pBuffer;

            RedMemCpy(gaulAlignedBuffer, &pbBuffer[ulSectorIdx * ulSectorSize], ulSectorSize);

            bSdError = BSP_SD_WriteBlocks_DMA(gaulAlignedBuffer, (ullSectorStart + ulSectorIdx), 1U);

            if(bSdError != MSD_OK)
            {
                redStat = -RED_EIO;
            }
          #if SD_STATUS_TIMEOUT > 0U
            else
            {
                redStat = CheckStatus();
            }
          #endif

            if(redStat != 0)
            {
                break;
            }
        }
    }

    return redStat;
```
This function (HAL_SD_WriteBlocks_DMA) take block logical address, but reliance edge high level functions pass block number). Can you explain exactly how the blocks are addressed?

**Comment by danielrlewis** [comment]
@SimonTechv:

> This function (HAL_SD_WriteBlocks_DMA) take block logical address, but reliance edge high level functions pass block number). Can you explain exactly how the blocks are addressed?

It may help to define terms.  Terminology differs, but I can explain the terminology we use in Reliance Edge:

- The _sector size_ is the minimum I/O size supported by the storage device, most commonly 512 bytes.
- A _sector number_ is a 0-based index of sector size chunks.
- The _block size_ is a power-of-two multiple of the sector size; it may be the same as the sector size, or it may be larger (up to 64KB).
- A _block number_ is a 0-based index of block size chunks.

The lower-level code within Reliance Edge uses sectors, while the higher-level code uses blocks.  The code which converts blocks to sectors may be found in core/driver/blockio.c.

In the code you quoted, `ullSectorStart` is a sector number and `ulSectorSize` is the sector size (which for an SD card is almost certainly `512`).  With the STM32 HAL code we were working with at the time, `BSP_SD_WriteBlocks_DMA()` took a sector number as its second argument and a sector count as its third argument (their code might not have used the "sector" terminology, but that's what it was).

However, the STM32 HAL code has minor differences between boards and is prone to changing over time.  Doing some quick research, it appears there are other versions of `BSP_SD_WriteBlocks_DMA()` which take a byte offset as the second argument, a `BlockSize` as the third argument, and a `NumOfBlocks` as the fourth argument.  Based on your question, I assume your STM32 HAL code is like this, or is some other variant which differs from what we were working with.

The thing to remember is that os/freertos/services/osbdev_stm32sdio.h (and the other `osbdev_*.h` files) is just intended to be an example.  You might need to modify it for your board and its HAL.  So, for example, if your version of `BSP_SD_WriteBlocks_DMA()` expects a byte offset, then you can modify the code to multiply the sector number by 512 (or shift it left by 9).

> It is also not entirely clear to me whether the function of processing an unaligned pointer is necessarily required? Internal buffers are initialized statically and must always be aligned along a 4 byte boundary.

The internal block buffers for Reliance Edge are aligned to `REDCONF_BUFFER_ALIGNMENT` bytes (see [here](https://github.com/tuxera/reliance-edge/blob/42c781f483e9b2c90c2496d55f844fb70b0aefad/core/driver/buffer.c#L137)) which is always at least 8 bytes.  However, that's not the only type of buffer which is written to the storage device.  If a file-level write is writing an entire aligned block, the buffer supplied to `red_write()` or `red_pwrite()` will be directly used for the transfer.  This buffer comes from the application; we have no control over its alignment and have to assume that it's potentially unaligned.
